### ISSUE TITLE
Migration discovery: move DCS to PaaS

### ISSUE THREAD

**Issue by federicoGDS** [alphagov/automate-roadmap#8]

**Comment by pauldougan** [comment]
let us know when you want to open the conversation around this

**Comment by federicoGDS** [comment]
> let us know when you want to open the conversation around this

@pauldougan we are having a kick-off tomorrow with the DCS team, will invite you!

**Comment by productfed** [comment]
The discovery is `DONE`
Please find the outcome [here](https://github.com/alphagov/doc-checking/blob/govuk-paas/doc/paas-discovery/README.md)
